runner: r001
SINGLE_FOLD: true
split:
    split_type: skf
    split_num: 5
    shuffle: true
    random_state: 71
loader:
    trn_sampler_type: random
    trn_batch_size: 48
    tst_sampler_type: sequential
    tst_batch_size: 48
    dataset_type: tse_segmentation_dataset
dataset:
    tokenizer_type: bert
    pretrained_model_name_or_path: bert-base-uncased
    do_lower_case: true
    max_length: 250
model:
    model_type: bert-segmentation
    pretrained_model_name_or_path: bert-base-uncased
    num_output_units: 250
fobj:
    fobj_type: bce
optimizer:
    optim_type: adam
    lr: 0.0001
scheduler:
    scheduler_type: cosine
train:
    max_epoch: 10
    warmup_epoch: 1
    thresh_unit: 0.05
predict:
    neutral_origin: true
invalid_labels:
    - ./inputs/nes_info/invalid_labels.csv
