description: "e009 small batch"
runner: r002
SINGLE_FOLD: false
split:
    split_type: skf
    split_num: 5
    shuffle: true
    random_state: 71
loader:
    trn_sampler_type: random
    trn_batch_size: 16
    tst_sampler_type: sequential
    tst_batch_size: 16
    dataset_type: tse_headtail_dataset
dataset:
    tokenizer_type: roberta_bytelevel_bpe
    pretrained_model_name_or_path: ./inputs/datasets/
    do_lower_case: true
    add_pair_prefix_space: false
    max_length: 125
model:
    model_type: roberta-headtail
    pretrained_model_name_or_path: roberta-base
    num_output_units: 125
fobj:
    fobj_type: ce
optimizer:
    optim_type: adam
    lr: 0.00003
scheduler:
    scheduler_type: cosine
train:
    max_epoch: 5
    warmup_epoch: 1
    thresh_unit: 0.05  # no meaning for head tail
    rm_neutral: false
predict:
    neutral_origin: true
invalid_labels:
    - ./inputs/nes_info/invalid_labels.csv
    - ./inputs/nes_info/invalid_labels_v2.csv
