description: "712 kernel https://www.kaggle.com/al0kharba/tensorflow-roberta-0-712"
runner: r002
SINGLE_FOLD: false
split:
    split_type: skf
    split_num: 5
    shuffle: true
    random_state: 71
loader:
    trn_sampler_type: random
    trn_batch_size: 8
    tst_sampler_type: sequential
    tst_batch_size: 8
dataset:
    dataset_type: tse_headtail_dataset_v2
    tokenizer_type: roberta_bytelevel_bpe
    pretrained_model_name_or_path: ./inputs/datasets/
    do_lower_case: true
    add_pair_prefix_space: false
    max_length: 96
model:
    model_type: roberta-headtail-v2
    pretrained_model_name_or_path: roberta-base
    num_output_units: 96
fobj:
    fobj_type: ce
optimizer:
    optim_type: adam
    lr: 0.00003
scheduler:
    scheduler_type: every_step
train:
    max_epoch: 5
    warmup_epoch: 0
    thresh_unit: 0.05  # no meaning for head tail
    rm_neutral: false
predict:
    neutral_origin: false
invalid_labels:
    # - ./inputs/nes_info/invalid_labels.csv
    # - ./inputs/nes_info/invalid_labels_v2.csv
